### ISSUE TITLE
Error parsing Element section

### ISSUE THREAD

**Issue by rxEckT** [danleh/wasabi#20] opened 2019-12-25 15:12 UTC
I have the following webassembly text file:

```wat
(module 
  (table 94 anyfunc)
  (elem (i32.const 43) 0)
  (elem (i32.const 45) 1)
  (elem (i32.const 60) 2)
  (elem (i32.const 62) 3)
  (elem (i32.const 91) 4)
  (elem (i32.const 93) 5)
  (elem (i32.const 46) 6)
  (func)
  (func)
  (func)
  (func)
  (func)
  (func)
  (func))
```

When compiled with wabt using wat2wasm (commit 76ff3af), the resulting binary could not be instrumented with Wasabi. The error received is [`Error: expected tag for ValType, got 0x00`](https://github.com/danleh/wasabi/blob/master/lib/wasm/binary_derive/src/lib.rs#L25-L40)

If compiled with [webassembly.studio](https://webassembly.studio) instead, Wasabi is able to instrument the binary.

---

I tried to narrow down the issue and I think the cause could be related to differences in how the Element section is encoded by the tools.

**With wat2wasm**
```
Contents of section Elem:
0000020: 0702 0041 2b0b 0001 0002 0041 2d0b 0001  ...A+......A-...
0000030: 0102 0041 3c0b 0001 0202 0041 3e0b 0001  ...A<......A>...
0000040: 0302 0041 db00 0b00 0104 0200 41dd 000b  ...A........A...
0000050: 0001 0502 0041 2e0b 0001 06              .....A.....
```

**With webassembly.studio**
```
Contents of section Elem:
0000020: 0700 412b 0b01 0000 412d 0b01 0100 413c  ..A+....A-....A<
0000030: 0b01 0200 413e 0b01 0300 41db 000b 0104  ....A>....A.....
0000040: 0041 dd00 0b01 0500 412e 0b01 06         .A......A....
```

*Output of `wasm-objdump -s`*

Any thoughts would be appreciated.

**Comment by danleh** [comment] 2019-12-26 13:29
Hi, sorry for the late reply. Interesting issue, thanks for posting.

I just started investigating, but cannot replicate it with my version of `wat2wasm`. Currently, I am using commit 8c0333856c1cfae7c735007ae232ee57dba21171 from Mon Sep 16 15:03:38 2019 of https://github.com/WebAssembly/wabt. My version of `wat2wasm` generates the same element section that you have posted for `webassembly.studio` below. If I checked correctly, you used a much more recent version of WABT, namely from 2019-12-23.

Could it be that WABT/`wat2wasm` introduced a regression here? Alternative explanation/hunch: You assembled with a new Wasm feature that Wasabi does not understand yet, e.g., shared memory, multiple table sections etc.? Essentially, the error means there was an unexpected tag for the ValType enum. The only four values Wasabi's Wasm parser can handle are those from the MVP (https://webassembly.github.io/spec/core/binary/types.html).

**Comment by danleh** [comment] 2019-12-26 13:42
Can you upload your assembled Wasm files by `wat2wasm` and `webassembly.studio`? For comparison, the one produced by WABT 8c0333856c1cfae7c735007ae232ee57dba21171 is here: https://github.com/danleh/wasabi/tree/5a60332ae0b081b7a826059122c2db03929b8fba/tests/inputs/issue-20.

**Comment by danleh** [comment] 2019-12-26 14:03
Some more hints for reading and comparing the two binaries by hand:
- `41` is the opcode for `i32.const` and `0b` the opcode for `end`. E.g., `41 2b 0b` is the encoding of `i32.const 43; end`. This is the initialization expression for the first element in the Element section. Similarly `41 2d 0b` (init of the next element) and so on.
- According to the binary format standard (https://webassembly.github.io/spec/core/binary/modules.html#element-section), the element section contains a vector of elements, where each element encodes the table index (should be 0x00, because there is only a single table), then the init expression, then a vector of function indices.
- So I think the first byte, 0x07, encodes the length of the vector of individual `elem`s. I also think 0x00 (the second byte in webassembly.studio and my version of WABT, the third byte in your version of WABT) encodes the table index.
- But why is there an additional 0x02 byte (the second byte) in between in the binary produced by your version of WABT? Is that an alternative encoding of 7 in LEB128? (I don't think so, that would be invalid LEB128.)

I am not a 100% sure, but think this is a WABT issue.

**Comment by danleh** [comment] 2019-12-26 14:09
Alright, I am pretty sure newer versions of WABT emit a binary that is **non-MVP compatible**, i.e., use features in the binary that are extensions. In this particular case, this WABT issue seems related: https://github.com/WebAssembly/wabt/issues/1268

There is nothing to do here for Wasabi, except:
- Implement support for extensions (unlikely at the current point in time, too little time).
- Make clearer in the documentation (Wasabi website, GitHub README) that we only support MVP features.

**Comment by rxEckT** [comment] 2019-12-26 14:26
Hi Daniel,

I failed to reproduce the issue using the sample .wat file I provided, it seems I reduced it by too much :sweat_smile:

I have successfully reproduced the issue using the following file:
```wat
(module 
  (type $t1 (func (param i32) (param i32)))
  (import "a" "a" (func $exec (type $t1)))
  ;; offset=448 tape
  ;; offset=512 out
  (memory $mem (export "b") 1)
  (data $mem (i32.const 0) "<<redacted>>")
  (table $interp 94 anyfunc)
  (elem $interp (i32.const 43) $inc)
  (elem $interp (i32.const 45) $dec)
  (elem $interp (i32.const 60) $shl)
  (elem $interp (i32.const 62) $shr)
  (elem $interp (i32.const 91) $start)
  (elem $interp (i32.const 93) $end)
  (elem $interp (i32.const 46) $prn)
  (global $pc (mut i32) (i32.const 0))
  (global $ptr (mut i32) (i32.const 0))
  (global $stack (mut i32) (i32.const 0))
  (global $out (mut i32) (i32.const 0))
  (func $inc
    get_global $ptr
    get_global $ptr
    i32.load8_u offset=448
    i32.const 1
    i32.add
    i32.store8 offset=448)
  (func $dec
    get_global $ptr
    get_global $ptr
    i32.load8_u offset=448
    i32.const 1
    i32.sub
    i32.store8 offset=448)
  (func $shl
    get_global $ptr
    i32.const 1
    i32.sub
    set_global $ptr)
  (func $shr
    get_global $ptr
    i32.const 1
    i32.add
    set_global $ptr)
  (func $start
    get_global $ptr
    i32.load8_u offset=448
    i32.eqz
    if
      call $skip
    else
      get_global $pc
      set_global $stack
    end)
  (func $end
    get_global $ptr
    i32.load8_u offset=448
    i32.eqz
    if
    else
      call $back
    end)
  (func $prn
    get_global $out
    get_global $ptr
    i32.load8_u offset=448
    i32.store8 offset=512
    get_global $out
    i32.const 1
    i32.add
    set_global $out)
  (func $skip (local i32)
    get_global $pc
    set_local 0
    loop $loop
      get_local 0
      i32.const 1
      i32.add
      tee_local 0
      i32.load8_u offset=0
      i32.const 93
      i32.ne
      br_if $loop
    end
    get_local 0
    set_global $pc)
  (func $back
    get_global $stack
    set_global $pc)
  (func $bf (local i32)
    i32.const 418
    set_local 0
    loop $loop
      get_local 0
      get_global $pc
      i32.load8_u offset=0
      call_indirect
      get_global $pc
      i32.const 1
      i32.add
      set_global $pc
      get_global $pc
      i32.gt_s
      br_if $loop
    end)
  (func $decode (param $key i32) (param $start i32) (param $length i32)
    get_local $length
    i32.const 0
    i32.gt_s
    if
      loop $loop
        get_local $start
        get_local $key
        get_local $start
        i32.load8_u
        i32.xor 
        i32.store8
        get_local $start
        i32.const 1
        i32.add
        set_local $start
        get_local $length
        i32.const 1
        i32.sub
        tee_local $length
        i32.const 0
        i32.gt_u
        br_if $loop
      end
    end)
  (func $entry (export "c")
    call $bf
    i32.const 29
    i32.const 512
    i32.const 41
    call $decode
    i32.const 512
    i32.const 41
    call $exec))
```

Indeed, as mentioned, it looks like a regression due to WebAssembly/wabt#1268, for I tried with my `76ff3af wabt` and your `8c0333 wabt` and they differ in the output.

Furthermore, the `8c0333 wasm-objdump` could not parse the Element section of the wasm produced by `76ff3af wat2wasm` too :sweat_smile:

---

`76ff3af wasm-objdump -x`
```
brainfuck.wasm:	file format wasm 0x1

Section Details:

Type[3]:
 - type[0] (i32, i32) -> nil
 - type[1] () -> nil
 - type[2] (i32, i32, i32) -> nil
Import[1]:
 - func[0] sig=0 <a.a> <- a.a
Function[12]:
 - func[1] sig=1
 - func[2] sig=1
 - func[3] sig=1
 - func[4] sig=1
 - func[5] sig=1
 - func[6] sig=1
 - func[7] sig=1
 - func[8] sig=1
 - func[9] sig=1
 - func[10] sig=1
 - func[11] sig=2
 - func[12] sig=1 <c>
Table[1]:
 - table[0] type=funcref initial=94
Memory[1]:
 - memory[0] pages: initial=1
Global[4]:
 - global[0] i32 mutable=1 - init i32=0
 - global[1] i32 mutable=1 - init i32=0
 - global[2] i32 mutable=1 - init i32=0
 - global[3] i32 mutable=1 - init i32=0
Export[2]:
 - memory[0] -> "b"
 - func[12] <c> -> "c"
Elem[7]:
 - segment[0] flags=2 table=0 count=1 - init i32=43
  - elem[43] = func[1]
 - segment[1] flags=2 table=0 count=1 - init i32=45
  - elem[45] = func[2]
 - segment[2] flags=2 table=0 count=1 - init i32=60
  - elem[60] = func[3]
 - segment[3] flags=2 table=0 count=1 - init i32=62
  - elem[62] = func[4]
 - segment[4] flags=2 table=0 count=1 - init i32=91
  - elem[91] = func[5]
 - segment[5] flags=2 table=0 count=1 - init i32=93
  - elem[93] = func[6]
 - segment[6] flags=2 table=0 count=1 - init i32=46
  - elem[46] = func[7]
Code[12]:
 - func[1] size=17
 - func[2] size=17
 - func[3] size=9
 - func[4] size=9
 - func[5] size=19
 - func[6] size=15
 - func[7] size=21
 - func[8] size=31
 - func[9] size=6
 - func[10] size=34
 - func[11] size=45
 - func[12] size=20 <c>
Data[1]:
 - segment[0] memory=0 size=12 - init i32=0
  - 0000000: 3c3c 7265 6461 6374 6564 3e3e            <<redacted>>
```
 
`8c0333 wasm-objdump -x`
```
brainfuck.wasm:	file format wasm 0x1
0000069: error: segment elem type must by funcref or anyref

Section Details:

Type[3]:
 - type[0] (i32, i32) -> nil
 - type[1] () -> nil
 - type[2] (i32, i32, i32) -> nil
Import[1]:
 - func[0] sig=0 <a.a> <- a.a
Function[12]:
 - func[1] sig=1
 - func[2] sig=1
 - func[3] sig=1
 - func[4] sig=1
 - func[5] sig=1
 - func[6] sig=1
 - func[7] sig=1
 - func[8] sig=1
 - func[9] sig=1
 - func[10] sig=1
 - func[11] sig=2
 - func[12] sig=1 <c>
Table[1]:
 - table[0] type=funcref initial=94
Memory[1]:
 - memory[0] pages: initial=1
Global[4]:
 - global[0] i32 mutable=1 - init i32=0
 - global[1] i32 mutable=1 - init i32=0
 - global[2] i32 mutable=1 - init i32=0
 - global[3] i32 mutable=1 - init i32=0
Export[2]:
 - memory[0] -> "b"
 - func[12] <c> -> "c"
Elem[7]:
 - segment[0] table=0 count=0 - init i32=43
Code[12]:
 - func[1] size=17
 - func[2] size=17
 - func[3] size=9
 - func[4] size=9
 - func[5] size=19
 - func[6] size=15
 - func[7] size=21
 - func[8] size=31
 - func[9] size=6
 - func[10] size=34
 - func[11] size=45
 - func[12] size=20 <c>
Data[1]:
 - segment[0] size=12 - init i32=0
  - 0000000: 3c3c 7265 6461 6374 6564 3e3e            <<redacted>>
```

Really grateful for you taking the time to respond to my issue!
[brainfuck-wasm.zip](https://github.com/danleh/wasabi/files/4002750/brainfuck-wasm.zip)

**Comment by danleh** [comment] 2019-12-26 14:31
Sure, happy to help and thanks for the files!
I will close this, as it is not an issue in Wasabi but rather in WABT. Feel free to re-open, if there is indeed something _we_ can do about it.

**Closed by danleh** 2019-12-26 14:31 UTC

**Comment by rxEckT** [comment] 2019-12-26 14:44
No problem!

I think the only actionable item would be for the wabt team to highlight any potential backwards-incompatible changes introduced (and provide an option to disable them). I would guess this issue is a side effect of the reference types proposal (but I'm not sure).
