### ISSUE TITLE
Wasm extensions

### ISSUE THREAD

**Issue by DCH81** [danleh/wasabi#44] opened 2024-07-22 11:23 UTC
Error: input file uses Wasm extensions, which are not supported yet by Wasabi

Can you add Wasm extensions support to wasabi ?

**Comment by danleh** [comment] 2024-07-22 17:06
I have very limited time at the moment to support Wasabi, so if it's substantial implementation effort the answer is likely no :/
Which extension do you need? (You can inspect the binary file with `wasm-objdump` or `wasm-upcodecnt` for exampe.)

See also PR #41 for a fork of Wasabi that does support more extensions. https://github.com/danleh/wasabi/pull/41

**Comment by doehyunbaek** [comment] 2024-07-23 01:18
Hi. @DCH81, I have a fork that supports upto Wasm 2.0 except SIMD(also I believe it supports some niche proposals like multi-memory), so if your use case doesn't require any further proposals, I think you will be good to go.

If you need SIMD, I'm willing to do the work to support it also, to make my fork support whole Wasm 2.0. So if that's the case, let me know.

**Comment by DCH81** [comment] 2024-07-23 07:05
Hey @danleh @doehyunbaek thank for your fast reply !
I tested the fork and still getting same error.
I edited the main.rs where it's checking if there is a not supported extension to that : 
`    // instrument Wasm and generate JavaScript
    let (mut module, _offsets, _warnings) = Module::from_file(opt.input_file)?;
    let used_extensions = module.metadata.used_extensions().collect::<Vec<_>>();
    if !used_extensions.is_empty() {
        println!("The following Wasm extensions are used and not supported by Wasabi:");
        for extension in used_extensions {
            println!("{:?}", extension); 
        }
        return Err(io_err("input file uses Wasm extensions, which are not supported yet by Wasabi").into());
    }`
    
   And im getting that result : 
  The following Wasm extensions are used and not supported by Wasabi:
    MultiValue
   
   Here is the wasm bytes :
[code.txt](https://github.com/user-attachments/files/16344943/code.txt)

**Comment by doehyunbaek** [comment] 2024-07-23 08:00
Could you try again with the updated fork? The branch with the PR was a little bit outdated.

Fortunately, it seems to work in this case(we support that proposal :p). So I think you're good to go.

If you can't find the fork, please try this branch https://github.com/doehyunbaek/wasabi/tree/candidate

**Comment by DCH81** [comment] 2024-07-23 08:35
Thank, that's working

**Comment by DCH81** [comment] 2024-07-23 09:44
> Could you try again with the updated fork? The branch with the PR was a little bit outdated.
> Fortunately, it seems to work in this case(we support that proposal :p). So I think you're good to go.
> If you can't find the fork, please try this branch https://github.com/doehyunbaek/wasabi/tree/candidate

When i use it  and try use wasm2wat on the new wasm file im getting that error : 0000004: error: bad magic value

**Comment by doehyunbaek** [comment] 2024-07-23 10:01
> And the file is reaallyyy bigg 50mo

The file getting big in itself is not something unexpected, should take a closer look to if there's any problem.
It adds a lot of code for the instrumentation.

> When im trying to use it : CompileError: WebAssembly.compile(): size 46445522 > maximum function size 7654321

How do you use it? Can you tell me how to reproduce the error?

**Comment by danleh** [comment] 2024-07-24 07:01
@DCH81 please spend a little bit of time yourself to diagnose the problem, the explanation for the error you are getting is literally the first Google result if you search for the posted error message. Most Wasm engines/VMs have agreed on certain limits, e.g., maximum module size, maximum function body size, maximum number of locals etc. You are hitting a limit with the instrumented module.

Some ideas for solutions (but whether they are applicable depends on your specific use-case, which is hard to tell with the little detail available):
- you could instrument only a subset of instructions/hooks, depending on what your analysis uses
- you could optimize the instrumented module with wasm-opt from the binaryen toolsuite, possibly that reduces the function size
- you could patch/recompile the engine you are running on to raise this particular limit
- possibly Wasabi's could be improved, but that would need a reproducer, eg. the input and output file, or you inspect the particular function yourself.

**Comment by DCH81** [comment] 2024-07-24 11:15
@danleh It's possible to hook only one function ?

**Comment by danleh** [comment] 2024-07-26 10:48
> Thank, that's working

Since the original issue seems to be resolved, I'm closing this.

**Closed by danleh** 2024-07-26 10:48 UTC
Labels: enhancement

**Comment by dropout1337** [comment] 2024-08-11 11:25
@DCH81 In the future do try do your own research before opening an issue to leech of other peoples time.
