### ISSUE TITLE
CORS block tutorial in newest Firefow

### ISSUE THREAD

**Issue by hjorthjort** [danleh/wasabi#27] opened 2020-07-13 17:44 UTC
Running the first tutorial (`hello.html`) in Firefox and clicking the button, the console repsonds with this error:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/hjort/code/wasabi/tutorial/task0/1-hello/hello.wasm. (Reason: CORS request not http).
```

**Comment by danleh** [comment] 2020-07-17 02:21
Sorry for the late reply. I think (but not 100% sure) this is because you are not serving the web application with a proper web server, but instead accessing it with the `file://` protocol. You could use, for example, Python's SimpleHTTPServer. For streaming compilation/instantiation, WebAssembly files must also be served with the correct MIME-type, see https://curiousprog.com/2018/10/08/serving-webassembly-files-with-a-development-web-server/.

Since this is really more about running WebAssembly in the browser in general, and not about Wasabi, I am closing this. Let me know if it is really caused by Wasabi.

**Closed by danleh** 2020-07-17 02:21 UTC
